main.py
from flask import Flask #importando a biblioteca
from routes.index import index_route
from routes.users import user_route


# Iniciando a aplicação
app = Flask(__name__) 

#Registrando as rotas da pasta "routes"
app.register_blueprint(index_route)
app.register_blueprint(user_route, url_prefix='/cadastro')

# Iniciando a execução.
app.run(debug=True) 

routes/index.py
from flask import Blueprint, render_template

index_route = Blueprint('index', __name__)

"""
    Rota /index/  (GET) - Pegar informação do bando de dados para logar

"""

@index_route.route('/')
def page_index():
    return render_template('index.html')

routes/users.py
from flask import Blueprint, render_template
from DB_fake.account import USERS

user_route = Blueprint('cadastro', __name__)

"""
    Rota /cadastro/ (POST) - Formulário de cadastro
    Rota /cadastrar/ (POST) - Mandar as informações para serem inseridas no BD

"""
@user_route.route('/')
def page_cadastro():
    return render_template('cadastro.html')


@user_route.route('/cadastrados')
def funcao_cadastrados():
    return render_template('cadastrados.html', users=USERS)

templates/cadastrados.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Usuários Cadastrados</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <h1>Usuários Cadastrados</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>CPF</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.nome }}</td>
                    <td>{{ user.idade }}</td>
                    <td>{{ user.cpf }}</td>
                    <td><button type="button" class="btn btn-primary">Editar</button></td>
                    <td><button type="button" class="btn btn-primary">Deletar</button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="actions">
        <a href="{{ url_for('cadastro.page_cadastro') }}" class="btn btn-dark">Cadastro</a>
        <a href="{{ url_for('index.page_index') }}" class="btn btn-dark">Início</a>
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    
</body>
</html>

templates/cadastro.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
</head>
<body>
    <div class="form-container">
        <h2>Cadastro de Usuário</h2>
        <form id="formCadastro">
            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" required>

            <label for="sobrenome">Sobrenome:</label>
            <input type="text" id="sobrenome" name="sobrenome" required>
            
            <label for="senha">Senha:</label>
            <input type="password" id="senha" name="senha" required>

            <label for="telefone">Telefone:</label>
            <input type="tel" id="telefone" name="telefone" placeholder="(XX) XXXXX-XXXX" required pattern="\([0-9]{2}\) [0-9]{5}-[0-9]{4}">

            <label for="endereco">Endereço:</label>
            <input type="text" id="endereco" name="endereco" required>

            <label for="cep">CEP:</label>
            <input type="text" id="cep" name="cep" placeholder="XXXXX-XXX" required pattern="\d{5}-\d{3}">

            <label for="idade">Idade:</label>
            <input type="number" id="idade" name="idade" min="0" required>

            <label for="cpf">CPF:</label>
            <input type="text" id="cpf" name="cpf" placeholder="XXX.XXX.XXX-XX" required pattern="\d{3}\.\d{3}\.\d{3}-\d{2}">

            <button type="submit">Salvar Usuário</button><br><br>

            <div id="errorMessages" class="error"></div>
            <div id="successMessage" class="success" style="display:none;">Usuário salvo com sucesso!</div>
        </form>
        <div class="form-action">
            <a href="{{ url_for('index.page_index') }}" class="login-button">Início</a>
        </div>

        <div class="form-action">
            <a href="{{ url_for('cadastro.funcao_cadastrados') }}" class="login-button">Cadastrados</a>
        </div>
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tela de Login - TESTE</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
</head>
<body>
    <div id="boneco"></div> <!-- Boneco que segue o mouse -->
    
    <div class="login-container">
        <h1>Login</h1>
        <form action="/login" method="post">
            <div class="input-field">
                <label for="nome">Nome</label>
                <input type="text" id="nome" name="nome" required>
            </div>
            <div class="input-field">
                <label for="senha">Senha</label>
                <input type="password" id="senha" name="senha" required>
            </div>
            <button type="submit" class="login-button">Entrar</button><br><br>

            <div class="form-action">
                <a href="{{ url_for('cadastro.page_cadastro') }}" class="login-button">Cadastro</a>
            </div>
        </form>
    </div>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    
</body>
</html>